// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filetansfer_service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownloadRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99eb70fcb0bd5354, []int{0}
}

func (m *DownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadRequest.Unmarshal(m, b)
}
func (m *DownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadRequest.Marshal(b, m, deterministic)
}
func (m *DownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadRequest.Merge(m, src)
}
func (m *DownloadRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadRequest.Size(m)
}
func (m *DownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadRequest proto.InternalMessageInfo

func (m *DownloadRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DownloadResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadResponse) Reset()         { *m = DownloadResponse{} }
func (m *DownloadResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadResponse) ProtoMessage()    {}
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_99eb70fcb0bd5354, []int{1}
}

func (m *DownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResponse.Unmarshal(m, b)
}
func (m *DownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResponse.Marshal(b, m, deterministic)
}
func (m *DownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResponse.Merge(m, src)
}
func (m *DownloadResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadResponse.Size(m)
}
func (m *DownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResponse proto.InternalMessageInfo

func (m *DownloadResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99eb70fcb0bd5354, []int{2}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UploadRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadResponse struct {
	Finished             bool     `protobuf:"varint,1,opt,name=finished,proto3" json:"finished,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_99eb70fcb0bd5354, []int{3}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *UploadResponse) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

type ListRequest struct {
	Directory            string   `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99eb70fcb0bd5354, []int{4}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

type ListResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode                 uint32   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_99eb70fcb0bd5354, []int{5}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListResponse) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func init() {
	proto.RegisterType((*DownloadRequest)(nil), "proto.DownloadRequest")
	proto.RegisterType((*DownloadResponse)(nil), "proto.DownloadResponse")
	proto.RegisterType((*UploadRequest)(nil), "proto.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "proto.UploadResponse")
	proto.RegisterType((*ListRequest)(nil), "proto.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "proto.ListResponse")
}

func init() { proto.RegisterFile("filetansfer_service.proto", fileDescriptor_99eb70fcb0bd5354) }

var fileDescriptor_99eb70fcb0bd5354 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4d, 0x4b, 0x3b, 0x31,
	0x10, 0xc6, 0xff, 0xf9, 0xb7, 0x96, 0x76, 0x6c, 0xad, 0xc4, 0xb7, 0xba, 0x78, 0x28, 0x01, 0x65,
	0x41, 0x28, 0x62, 0x4f, 0x9e, 0x7a, 0xf1, 0x50, 0x44, 0x3c, 0x44, 0x3d, 0x4b, 0xec, 0x4e, 0x69,
	0xa0, 0xdd, 0xac, 0x49, 0x54, 0xf4, 0xe3, 0xf9, 0xc9, 0x24, 0xc9, 0xbe, 0x75, 0x3d, 0xed, 0xcc,
	0xc3, 0xb3, 0xbf, 0x99, 0x79, 0x02, 0xa7, 0x4b, 0xb9, 0x46, 0x2b, 0x52, 0xb3, 0x44, 0xfd, 0x62,
	0x50, 0x7f, 0xc8, 0x05, 0x4e, 0x32, 0xad, 0xac, 0xa2, 0x3b, 0xfe, 0xc3, 0xce, 0x61, 0x78, 0xab,
	0x3e, 0xd3, 0xb5, 0x12, 0x09, 0xc7, 0xb7, 0x77, 0x34, 0x96, 0x52, 0x68, 0xa7, 0x62, 0x83, 0x23,
	0x32, 0x26, 0x71, 0x8f, 0xfb, 0x9a, 0x5d, 0xc0, 0x7e, 0x65, 0x33, 0x99, 0x4a, 0x0d, 0x3a, 0x5f,
	0x22, 0xac, 0xf0, 0xbe, 0x3e, 0xf7, 0x35, 0x9b, 0xc1, 0xe0, 0x39, 0xab, 0xc3, 0x22, 0xe8, 0xba,
	0x1d, 0x1e, 0x2a, 0x60, 0xd9, 0x97, 0x80, 0xff, 0x35, 0xc0, 0x1c, 0xf6, 0x0a, 0x40, 0x3e, 0xc6,
	0x13, 0x52, 0x69, 0x56, 0x98, 0x78, 0x42, 0x97, 0x97, 0x7d, 0x41, 0x9f, 0x0b, 0xb3, 0xf2, 0x94,
	0x9c, 0xee, 0x7a, 0x76, 0x09, 0xbb, 0xf7, 0xd2, 0xd8, 0x62, 0x91, 0x33, 0xe8, 0x25, 0x52, 0xe3,
	0xc2, 0x2a, 0xfd, 0x95, 0x6f, 0x52, 0x09, 0xec, 0x0e, 0xfa, 0xc1, 0x5c, 0xdd, 0xd6, 0xcc, 0xc0,
	0x69, 0x46, 0x7e, 0xa3, 0x1f, 0xd4, 0xe2, 0xbe, 0x76, 0xda, 0x46, 0x25, 0x38, 0x6a, 0x8d, 0x49,
	0x3c, 0xe0, 0xbe, 0xbe, 0xfe, 0x21, 0x30, 0x7c, 0xd2, 0x21, 0xf4, 0xc7, 0x90, 0x39, 0x9d, 0x41,
	0xb7, 0xc8, 0x8f, 0x1e, 0x87, 0x17, 0x98, 0x34, 0x72, 0x8f, 0x4e, 0xfe, 0xe8, 0x61, 0x19, 0xf6,
	0xef, 0x8a, 0xd0, 0x1b, 0xe8, 0x84, 0x5c, 0xe8, 0x61, 0x6e, 0xdb, 0xca, 0x39, 0x3a, 0x6a, 0xa8,
	0xc5, 0xaf, 0x31, 0xa1, 0x53, 0x68, 0xbb, 0xdb, 0x28, 0xcd, 0x2d, 0xb5, 0x54, 0xa2, 0x83, 0x2d,
	0xad, 0x9a, 0xf7, 0xda, 0xf1, 0xfa, 0xf4, 0x37, 0x00, 0x00, 0xff, 0xff, 0x68, 0x76, 0xa1, 0xee,
	0x42, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransferServiceClient interface {
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (TransferService_DownloadClient, error)
	Upload(ctx context.Context, opts ...grpc.CallOption) (TransferService_UploadClient, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (TransferService_ListClient, error)
}

type transferServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransferServiceClient(cc *grpc.ClientConn) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (TransferService_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TransferService_serviceDesc.Streams[0], "/proto.TransferService/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &transferServiceDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransferService_DownloadClient interface {
	Recv() (*DownloadResponse, error)
	grpc.ClientStream
}

type transferServiceDownloadClient struct {
	grpc.ClientStream
}

func (x *transferServiceDownloadClient) Recv() (*DownloadResponse, error) {
	m := new(DownloadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transferServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (TransferService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TransferService_serviceDesc.Streams[1], "/proto.TransferService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &transferServiceUploadClient{stream}
	return x, nil
}

type TransferService_UploadClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type transferServiceUploadClient struct {
	grpc.ClientStream
}

func (x *transferServiceUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transferServiceUploadClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transferServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (TransferService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TransferService_serviceDesc.Streams[2], "/proto.TransferService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &transferServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransferService_ListClient interface {
	Recv() (*ListResponse, error)
	grpc.ClientStream
}

type transferServiceListClient struct {
	grpc.ClientStream
}

func (x *transferServiceListClient) Recv() (*ListResponse, error) {
	m := new(ListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransferServiceServer is the server API for TransferService service.
type TransferServiceServer interface {
	Download(*DownloadRequest, TransferService_DownloadServer) error
	Upload(TransferService_UploadServer) error
	List(*ListRequest, TransferService_ListServer) error
}

// UnimplementedTransferServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransferServiceServer struct {
}

func (*UnimplementedTransferServiceServer) Download(req *DownloadRequest, srv TransferService_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (*UnimplementedTransferServiceServer) Upload(srv TransferService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (*UnimplementedTransferServiceServer) List(req *ListRequest, srv TransferService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterTransferServiceServer(s *grpc.Server, srv TransferServiceServer) {
	s.RegisterService(&_TransferService_serviceDesc, srv)
}

func _TransferService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransferServiceServer).Download(m, &transferServiceDownloadServer{stream})
}

type TransferService_DownloadServer interface {
	Send(*DownloadResponse) error
	grpc.ServerStream
}

type transferServiceDownloadServer struct {
	grpc.ServerStream
}

func (x *transferServiceDownloadServer) Send(m *DownloadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TransferService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransferServiceServer).Upload(&transferServiceUploadServer{stream})
}

type TransferService_UploadServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type transferServiceUploadServer struct {
	grpc.ServerStream
}

func (x *transferServiceUploadServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transferServiceUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TransferService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransferServiceServer).List(m, &transferServiceListServer{stream})
}

type TransferService_ListServer interface {
	Send(*ListResponse) error
	grpc.ServerStream
}

type transferServiceListServer struct {
	grpc.ServerStream
}

func (x *transferServiceListServer) Send(m *ListResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _TransferService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _TransferService_Download_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _TransferService_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "List",
			Handler:       _TransferService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "filetansfer_service.proto",
}
